### ISSUE TITLE
inplementing join operations

### ISSUE THREAD

**Issue by fabiangigler** [friedolinfoerder/wp-activerecord#2]
Hey, are you planning to create abstraction functions for mysql join operations as well?

**Comment by friedolinfoerder** [comment]
I will have a look in the next days. It shouldn't be a big deal.
If you have some implementation feel free to make a PR.

**Comment by bayareabuilder** [comment]
Just found this repo. Excellent Work!  2nd on the join operations.  That's the only thing I see missing. 

PS. Let me know if you have a TipJar somewhere,  I'd love to contribute a few bucks toward your efforts.

**Comment by nonsensecreativity** [comment]
+1 for this

**Comment by friedolinfoerder** [comment]
I've added the join-Method. You can find the details in the readme.
It's a very basic implementation. If you need more functionality just open an issue...

**Comment by fabiangigler** [comment]
awesome, thanks

**Comment by nonsensecreativity** [comment]
Awesome!!
