### ISSUE TITLE
Error with constructor

### ISSUE THREAD

**Issue by alana314** [friedolinfoerder/wp-activerecord#3]
Hello,
Thanks for making this library. I'm having trouble with the following:
```
require_once(WP_PLUGIN_DIR . '/my-plugin/ActiveRecord.php');
			
			class Brand extends \wp_activerecord\ActiveRecord {
			    protected static $table_name = 'brands';
			}
			// $rows = Brand::query()
		 //  ->select('id', 'name')
		 //  ->get();
			$rows = Brand::get(1);
```
Both Brand::query() and Brand::get() give me the same error:
Uncaught TypeError: Argument 1 passed to wp_activerecord\ActiveRecord::__construct() must be of the type array, null given

**Comment by alana314** [comment]
I can get it to work if I use ARRAY_A instead of OBJECT_K for the wpdb methods.
https://github.com/friedolinfoerder/wp-activerecord/pull/4

**Comment by Blair2004** [comment]
I get the same issue.
